name: projects
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_storage: ^12.1.9
  firebase_database: ^11.0.19
  firebase_ui_auth: ^1.16.1
  geolocator: ^14.0.0
  permission_handler: ^12.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  table_calendar: ^3.0.8
  flutter_local_notifications: ^19.1.0
  intl: ^0.20.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

